- README.md
- cmd/cl001/ac001/command.go
- cmd/cl001/ac001/error.go
- cmd/cl001/ac001/execute/command.go
- cmd/cl001/ac001/execute/error.go
- cmd/cl001/ac001/execute/flag.go
- cmd/cl001/ac001/execute/runner.go
- cmd/cl001/ac001/explain/command.go
- cmd/cl001/ac001/explain/error.go
- cmd/cl001/ac001/explain/flag.go
- cmd/cl001/ac001/explain/runner.go
- cmd/cl001/ac001/flag.go
- cmd/cl001/ac001/runner.go
- cmd/cl001/command.go
- cmd/cl001/error.go
- cmd/cl001/flag.go
- cmd/cl001/runner.go
- cmd/command.go
- cmd/completion/command.go
- cmd/completion/error.go
- cmd/completion/flag.go
- cmd/completion/runner.go
- cmd/completion/zsh/command.go
- cmd/completion/zsh/error.go
- cmd/completion/zsh/flag.go
- cmd/completion/zsh/runner.go
- docs/completion.md
- docs/structure.md
- pkg/action/ac001/ac001.go
- pkg/action/spec.go
> add basic command structure

- pkg/action/ac001/error.go
- pkg/action/ac001/executor.go
- pkg/action/ac002/error.go
- pkg/action/ac002/executor.go
> add cl001/ac002 for checking worker nodes

- cmd/command.go
- cmd/gen/ac/command.go
- cmd/gen/ac/error.go
- cmd/gen/ac/flag.go
- cmd/gen/ac/runner.go
- cmd/gen/ac/template/command.go
- cmd/gen/ac/template/error.go
- cmd/gen/ac/template/execute/command.go
- cmd/gen/ac/template/execute/error.go
- cmd/gen/ac/template/execute/flag.go
- cmd/gen/ac/template/execute/runner.go
- cmd/gen/ac/template/explain/command.go
- cmd/gen/ac/template/explain/error.go
- cmd/gen/ac/template/explain/flag.go
- cmd/gen/ac/template/explain/runner.go
- cmd/gen/ac/template/flag.go
- cmd/gen/ac/template/runner.go
- cmd/gen/cl/command.go
- cmd/gen/cl/error.go
- cmd/gen/cl/flag.go
- cmd/gen/cl/runner.go
- cmd/gen/command.go
- cmd/gen/error.go
- cmd/gen/flag.go
- cmd/gen/runner.go
> add generate command structure

- cmd/cl001/ac004/execute/zz_generated.command.go
- cmd/cl001/ac004/execute/zz_generated.error.go
- cmd/cl001/ac004/execute/zz_generated.flag.go
- cmd/cl001/ac004/execute/zz_generated.runner.go
- cmd/cl001/ac004/explain/zz_generated.command.go
- cmd/cl001/ac004/explain/zz_generated.error.go
- cmd/cl001/ac004/explain/zz_generated.flag.go
- cmd/cl001/ac004/explain/zz_generated.runner.go
- cmd/cl001/ac004/zz_generated.command.go
- cmd/cl001/ac004/zz_generated.error.go
- cmd/cl001/ac004/zz_generated.flag.go
- cmd/cl001/ac004/zz_generated.runner.go
- pkg/action/cl001/ac004/executor.go
- pkg/action/cl001/ac004/explainer.go
- pkg/action/cl001/ac004/zz_generated.error.go
- pkg/action/cl001/ac004/zz_generated.executor.go
- pkg/action/cl001/ac004/zz_generated.explainer.go
> add ac004 to cl001

- go.mod
- go.sum
- pkg/key/key.go
- pkg/release/release.go
- pkg/release/type.go
> add release package for further use

- pkg/key/key.go
> fix latest release version

- docs/environment.md
> extend docs to explain tenant cluster ID management

- cmd/cl001/ac000/execute/zz_generated.command.go
- cmd/cl001/ac000/execute/zz_generated.error.go
- cmd/cl001/ac000/execute/zz_generated.flag.go
- cmd/cl001/ac000/execute/zz_generated.runner.go
- cmd/cl001/ac000/explain/zz_generated.command.go
- cmd/cl001/ac000/explain/zz_generated.error.go
- cmd/cl001/ac000/explain/zz_generated.flag.go
- cmd/cl001/ac000/explain/zz_generated.runner.go
- cmd/cl001/ac000/zz_generated.command.go
- cmd/cl001/ac000/zz_generated.error.go
- cmd/cl001/ac000/zz_generated.flag.go
- cmd/cl001/ac000/zz_generated.runner.go
- cmd/cl001/zz_generated.command.go
- pkg/action/cl001/ac000/executor.go
- pkg/action/cl001/ac000/explainer.go
- pkg/action/cl001/ac000/zz_generated.error.go
- pkg/action/cl001/ac000/zz_generated.executor.go
- pkg/action/cl001/ac000/zz_generated.explainer.go
I want to play around with ideas for implementing a test plan so that we can execute all actions automatically in a given order. All the code here is only generated. 
```
awscnfm generate action -c cl001 -a ac000
awscnfm generate cluster -c cl001
```
> add action ac000 for test plan

- cmd/generate/action/template/pkg/action/executor_custom.go
> fix action generation formatting

- cmd/cl001/ac000/execute/zz_generated.runner.go
- cmd/cl001/ac001/execute/zz_generated.runner.go
- cmd/cl001/ac002/execute/zz_generated.runner.go
- cmd/cl001/ac003/execute/zz_generated.runner.go
- cmd/cl001/ac004/execute/zz_generated.runner.go
- cmd/generate/action/template/cmd/execute/runner.go
- cmd/generate/action/template/pkg/action/executor.go
- pkg/action/cl001/ac000/executor.go
- pkg/action/cl001/ac000/zz_generated.executor.go
- pkg/action/cl001/ac001/zz_generated.executor.go
- pkg/action/cl001/ac002/zz_generated.executor.go
- pkg/action/cl001/ac003/zz_generated.executor.go
- pkg/action/cl001/ac004/zz_generated.executor.go
This work goes towards defining a test plan in action `ac000`. It will be great. With this every command can discover the command structure and even execute them. The idea is to let action `ac000` define a test plan and explain and execute it accordingly.
> inject cobra commands for recursive discovery

- go.mod
- pkg/action/cl001/ac000/plan.go
- pkg/plan/plan.go
This PR provides a suggestion on how the plan for a cluster scope might be defined. The plan provides all information to explain and execute the test suite.
> add plan structure

- go.mod
- go.sum
- pkg/action/cl001/ac000/explainer.go
- pkg/table/table.go
```
$ awscnfm cl001 ac000 explain
Execute the conformance test plan of this cluster scope. Actions below are
executed in order. A tenant cluster is conform if the plan executes without
errors.
ACTION  COMMENT
ac001   create cluster
ac002   check master count
ac003   check worker count
ac004   not yet implemented
```
> explain test plan command for ac000

- pkg/action/cl001/ac000/explainer.go
- pkg/action/cl001/ac000/plan.go
- pkg/plan/backoff.go
- pkg/plan/executor.go
- pkg/plan/step.go
With this it is better explained how long each step and the whole plan execution can take in total. 
```
$ awscnfm cl001 ac000 explain
Execute the conformance test plan of this cluster scope. Actions below are
executed in order. A tenant cluster is conform if the plan executes without
errors. Plan execution might take up to 1h54m20s.
ACTION  RETRY  WAIT     COMMENT
ac001   3m0s   24m0s    create cluster
ac002   2s     10s      check master count
ac003   2s     10s      check worker count
ac004   9m0s   1h30m0s  delete cluster
```
> improve plan explanation by adding time information

- pkg/action/cl001/ac000/plan.go
Follow up of https://github.com/giantswarm/awscnfm/pull/67. Fixing the plan to get the order right again.
> fix plan after ac002 insertion

- README.md
- docs/introduction.md
As discussed in our most recent retro here we want to provide more information on how anything works with `awscnfm`.
> extend docs with introduction

- README.md
- docs/generation.md
- docs/introduction.md
> extend the docs a bit further

- pkg/action/all.go
Successor of https://github.com/giantswarm/awscnfm/pull/61.
> make fetching all actions more graceful

- cmd/generate/cluster/template/command.go
Follow up of https://github.com/giantswarm/awscnfm/pull/63. I got issues now with cluster generation. See https://github.com/giantswarm/awscnfm/pull/72.
> fix cluster generation for cases with and without actions

- cmd/cl001/ac006/execute/zz_generated.command.go
- cmd/cl001/ac006/execute/zz_generated.error.go
- cmd/cl001/ac006/execute/zz_generated.flag.go
- cmd/cl001/ac006/execute/zz_generated.runner.go
- cmd/cl001/ac006/explain/zz_generated.command.go
- cmd/cl001/ac006/explain/zz_generated.error.go
- cmd/cl001/ac006/explain/zz_generated.flag.go
- cmd/cl001/ac006/explain/zz_generated.runner.go
- cmd/cl001/ac006/zz_generated.command.go
- cmd/cl001/ac006/zz_generated.error.go
- cmd/cl001/ac006/zz_generated.flag.go
- cmd/cl001/ac006/zz_generated.runner.go
- cmd/cl001/zz_generated.command.go
- pkg/action/cl001/ac006/executor.go
- pkg/action/cl001/ac006/explainer.go
- pkg/action/cl001/ac006/zz_generated.error.go
- pkg/action/cl001/ac006/zz_generated.executor.go
- pkg/action/cl001/ac006/zz_generated.explainer.go
This is just generated code. Adding business logic in the next PR.
> add action ac006 to cluster cl001 for checking CRs after deletion

- pkg/key/key.go
Just aligning with the latest release based on https://github.com/giantswarm/releases. When we agree on staying aligned with the release cycle we need to keep this version up to date as well and make sure we change it before we tag and release the tool.
> update release to v12.1.0

- cmd/cl001/ac007/execute/zz_generated.command.go
- cmd/cl001/ac007/execute/zz_generated.error.go
- cmd/cl001/ac007/execute/zz_generated.flag.go
- cmd/cl001/ac007/execute/zz_generated.runner.go
- cmd/cl001/ac007/explain/zz_generated.command.go
- cmd/cl001/ac007/explain/zz_generated.error.go
- cmd/cl001/ac007/explain/zz_generated.flag.go
- cmd/cl001/ac007/explain/zz_generated.runner.go
- cmd/cl001/ac007/zz_generated.command.go
- cmd/cl001/ac007/zz_generated.error.go
- cmd/cl001/ac007/zz_generated.flag.go
- cmd/cl001/ac007/zz_generated.runner.go
- cmd/cl001/zz_generated.command.go
- pkg/action/cl001/ac007/executor.go
- pkg/action/cl001/ac007/explainer.go
- pkg/action/cl001/ac007/zz_generated.error.go
- pkg/action/cl001/ac007/zz_generated.executor.go
- pkg/action/cl001/ac007/zz_generated.explainer.go
> generate action ac007

- cmd/cl001/ac008/execute/zz_generated.command.go
- cmd/cl001/ac008/execute/zz_generated.error.go
- cmd/cl001/ac008/execute/zz_generated.flag.go
- cmd/cl001/ac008/execute/zz_generated.runner.go
- cmd/cl001/ac008/explain/zz_generated.command.go
- cmd/cl001/ac008/explain/zz_generated.error.go
- cmd/cl001/ac008/explain/zz_generated.flag.go
- cmd/cl001/ac008/explain/zz_generated.runner.go
- cmd/cl001/ac008/zz_generated.command.go
- cmd/cl001/ac008/zz_generated.error.go
- cmd/cl001/ac008/zz_generated.flag.go
- cmd/cl001/ac008/zz_generated.runner.go
- cmd/cl001/zz_generated.command.go
- pkg/action/cl001/ac008/executor.go
- pkg/action/cl001/ac008/explainer.go
- pkg/action/cl001/ac008/zz_generated.error.go
- pkg/action/cl001/ac008/zz_generated.executor.go
- pkg/action/cl001/ac008/zz_generated.explainer.go
> generate action ac008

- go.mod
- go.sum
- pkg/action/cl001/ac000/plan.go
- pkg/action/cl001/ac001/explainer.go
- pkg/action/cl001/ac005/crs.go
- pkg/action/cl001/ac005/executor.go
- pkg/action/cl001/ac005/explainer.go
> add nodepool action in ac005

- pkg/action/cl001/ac000/plan.go
> fix plan backoff for waiting for node pool creation

- CHANGELOG.md
- pkg/action/cl001/ac000/plan.go
- pkg/action/cl001/ac006/error.go
- pkg/action/cl001/ac006/executor.go
- pkg/action/cl001/ac006/explainer.go
check if host network pods matches with the number of pods we expect from k8scloudconfig
> master host network action

- cmd/insert/action/flag.go
- cmd/insert/action/runner.go
- pkg/action/incr.go
- pkg/action/incr_test.go
- pkg/action/lower.go
- pkg/action/lower_test.go
I want to split my work and ship this part already separately. My goal is to implement `awscnfm insert action`. Here is only the mapping computation. Next up is the file system magic. Stay tuned.
> compute insert mapping for code generation

- CHANGELOG.md
- pkg/action/cl001/ac000/plan.go
- pkg/action/cl001/ac007/error.go
- pkg/action/cl001/ac007/executor.go
- pkg/action/cl001/ac007/explainer.go
add a new action fo host network worker verification
> worker host network action

- pkg/action/cl001/ac001/crs.go
- pkg/action/cl001/ac005/crs.go
- pkg/key/key.go
- pkg/project/project.go
With releasing `awscnfm` we already got out of sync with the actual release version we use. This here aims to keep the code to be more maintainable.
> simplify release version usage

- docs/using.md
> add docs about release version management

- pkg/action/cl001/ac002/executor.go
- pkg/action/cl001/ac003/executor.go
- pkg/action/cl001/ac004/executor.go
- pkg/action/cl001/ac006/executor.go
- pkg/action/cl001/ac007/executor.go
Following up on https://github.com/giantswarm/awscnfm/pull/113 this PR makes use of the configured scope.
> use configured scope

- pkg/action/cl001/ac001/crs.go
- pkg/action/cl001/ac006/executor.go
- pkg/action/cl001/ac007/executor.go
> Fix hostnetwork checks

- pkg/action/cl001/ac001/crs.go
- pkg/action/cl001/ac005/crs.go
- pkg/release/patch.go
- pkg/release/patch_test.go
- pkg/release/release.go
In preparation for upgrade tests we need logic to find the latest major, minor and patch version of the predecessor of the current release. This refactoring prepares for the next steps required. I need to check if I am happy with that still but so far this was what I could come up with.
> refactor patch release management

- pkg/release/major.go
- pkg/release/major_test.go
- pkg/release/minor.go
- pkg/release/patch.go
- pkg/release/patch_test.go
Preparing for upgrades, this is to resolve the latest previous major version. I noticed there were some test cases for minor and patch missing and added them here.
> add major release search

- pkg/release/major.go
- pkg/release/minor.go
> fix naming

- cmd/generate/cluster/template/command.go
This PR fixes a minor issue when you generate only a new cluster scope itself. We should start writing golden file tests for the code generation. I am not getting into this now because my objective is writing an upgrade test. This is more important now.
> fix generation

- cmd/cl002/zz_generated.command.go
- cmd/cl002/zz_generated.error.go
- cmd/cl002/zz_generated.flag.go
- cmd/cl002/zz_generated.runner.go
- cmd/command.go
We need a new cluster scope for the upgrade tests we want to write.
> generate new cluster scope cl002

- cmd/cl002/ac001/execute/zz_generated.command.go
- cmd/cl002/ac001/execute/zz_generated.error.go
- cmd/cl002/ac001/execute/zz_generated.flag.go
- cmd/cl002/ac001/execute/zz_generated.runner.go
- cmd/cl002/ac001/explain/zz_generated.command.go
- cmd/cl002/ac001/explain/zz_generated.error.go
- cmd/cl002/ac001/explain/zz_generated.flag.go
- cmd/cl002/ac001/explain/zz_generated.runner.go
- cmd/cl002/ac001/zz_generated.command.go
- cmd/cl002/ac001/zz_generated.error.go
- cmd/cl002/ac001/zz_generated.flag.go
- cmd/cl002/ac001/zz_generated.runner.go
- pkg/action/cl002/ac001/executor.go
- pkg/action/cl002/ac001/explainer.go
- pkg/action/cl002/ac001/zz_generated.error.go
- pkg/action/cl002/ac001/zz_generated.executor.go
- pkg/action/cl002/ac001/zz_generated.explainer.go
All this code is generated by the tool itself. We will use `ac001` for cluster creation.
> add action ac001 to cluster scope cl002

- pkg/release/components.go
- pkg/release/spec.go
- pkg/release/version.go
Trying to implement the upgrade tests I noticed there is a bit of functionality missing. I tried to define the interface extension here.
> extend release resolver interface

- cmd/cl002/ac000/execute/zz_generated.command.go
- cmd/cl002/ac000/execute/zz_generated.error.go
- cmd/cl002/ac000/execute/zz_generated.flag.go
- cmd/cl002/ac000/execute/zz_generated.runner.go
- cmd/cl002/ac000/explain/zz_generated.command.go
- cmd/cl002/ac000/explain/zz_generated.error.go
- cmd/cl002/ac000/explain/zz_generated.flag.go
- cmd/cl002/ac000/explain/zz_generated.runner.go
- cmd/cl002/ac000/zz_generated.command.go
- cmd/cl002/ac000/zz_generated.error.go
- cmd/cl002/ac000/zz_generated.flag.go
- cmd/cl002/ac000/zz_generated.runner.go
- pkg/action/cl002/ac000/executor.go
- pkg/action/cl002/ac000/explainer.go
- pkg/action/cl002/ac000/zz_generated.error.go
- pkg/action/cl002/ac000/zz_generated.executor.go
- pkg/action/cl002/ac000/zz_generated.explainer.go
Continuing to work on the upgrade tests. This PR adds the generated code for action `ac000` which will contain the test plan.
> add action ac000 to cluster scope cl002

- pkg/action/cl002/ac000/executor.go
- pkg/action/cl002/ac000/explainer.go
- pkg/action/cl002/ac000/plan.go
Follow up of https://github.com/giantswarm/awscnfm/pull/130. Implementing the plan logic here.
> implement plan for cluster scope cl002

- cmd/cl002/ac002/execute/zz_generated.command.go
- cmd/cl002/ac002/execute/zz_generated.error.go
- cmd/cl002/ac002/execute/zz_generated.flag.go
- cmd/cl002/ac002/execute/zz_generated.runner.go
- cmd/cl002/ac002/explain/zz_generated.command.go
- cmd/cl002/ac002/explain/zz_generated.error.go
- cmd/cl002/ac002/explain/zz_generated.flag.go
- cmd/cl002/ac002/explain/zz_generated.runner.go
- cmd/cl002/ac002/zz_generated.command.go
- cmd/cl002/ac002/zz_generated.error.go
- cmd/cl002/ac002/zz_generated.flag.go
- cmd/cl002/ac002/zz_generated.runner.go
- pkg/action/cl002/ac002/executor.go
- pkg/action/cl002/ac002/explainer.go
- pkg/action/cl002/ac002/zz_generated.error.go
- pkg/action/cl002/ac002/zz_generated.executor.go
- pkg/action/cl002/ac002/zz_generated.explainer.go
Adding `ac002` to cluster scope `cl002` to wait for cluster creation. Note that this PR only contains the generated code.
> add action ac002 to cluster scope cl002

- pkg/action/cl002/ac002/executor.go
- pkg/action/cl002/ac002/explainer.go
Follow up of https://github.com/giantswarm/awscnfm/pull/132.
> implement waiting for cluster being created in cluster scope cl002

- cmd/cl002/ac003/execute/zz_generated.command.go
- cmd/cl002/ac003/execute/zz_generated.error.go
- cmd/cl002/ac003/execute/zz_generated.flag.go
- cmd/cl002/ac003/execute/zz_generated.runner.go
- cmd/cl002/ac003/explain/zz_generated.command.go
- cmd/cl002/ac003/explain/zz_generated.error.go
- cmd/cl002/ac003/explain/zz_generated.flag.go
- cmd/cl002/ac003/explain/zz_generated.runner.go
- cmd/cl002/ac003/zz_generated.command.go
- cmd/cl002/ac003/zz_generated.error.go
- cmd/cl002/ac003/zz_generated.flag.go
- cmd/cl002/ac003/zz_generated.runner.go
- pkg/action/cl002/ac003/executor.go
- pkg/action/cl002/ac003/explainer.go
- pkg/action/cl002/ac003/zz_generated.error.go
- pkg/action/cl002/ac003/zz_generated.executor.go
- pkg/action/cl002/ac003/zz_generated.explainer.go
Adding the generated code for the upgrade step.
> add ac003 to cl002

- cmd/cl002/ac004/execute/zz_generated.command.go
- cmd/cl002/ac004/execute/zz_generated.error.go
- cmd/cl002/ac004/execute/zz_generated.flag.go
- cmd/cl002/ac004/execute/zz_generated.runner.go
- cmd/cl002/ac004/explain/zz_generated.command.go
- cmd/cl002/ac004/explain/zz_generated.error.go
- cmd/cl002/ac004/explain/zz_generated.flag.go
- cmd/cl002/ac004/explain/zz_generated.runner.go
- cmd/cl002/ac004/zz_generated.command.go
- cmd/cl002/ac004/zz_generated.error.go
- cmd/cl002/ac004/zz_generated.flag.go
- cmd/cl002/ac004/zz_generated.runner.go
- cmd/cl002/zz_generated.command.go
- pkg/action/cl002/ac004/executor.go
- pkg/action/cl002/ac004/explainer.go
- pkg/action/cl002/ac004/zz_generated.error.go
- pkg/action/cl002/ac004/zz_generated.executor.go
- pkg/action/cl002/ac004/zz_generated.explainer.go
Generating a new action which is run after the actual cluster upgrade. As a next step this will get business logic added to find out if the upgrade was finished.
> generate ac004 for cl002

- pkg/action/cl002/ac000/plan.go
This adds some test plan details so that the test plan can be executed. Note that deletion is not yet implemented. I will work on this next.
> implement upgrade plan

- cmd/cl002/ac005/execute/zz_generated.command.go
- cmd/cl002/ac005/execute/zz_generated.error.go
- cmd/cl002/ac005/execute/zz_generated.flag.go
- cmd/cl002/ac005/execute/zz_generated.runner.go
- cmd/cl002/ac005/explain/zz_generated.command.go
- cmd/cl002/ac005/explain/zz_generated.error.go
- cmd/cl002/ac005/explain/zz_generated.flag.go
- cmd/cl002/ac005/explain/zz_generated.runner.go
- cmd/cl002/ac005/zz_generated.command.go
- cmd/cl002/ac005/zz_generated.error.go
- cmd/cl002/ac005/zz_generated.flag.go
- cmd/cl002/ac005/zz_generated.runner.go
- cmd/cl002/zz_generated.command.go
- pkg/action/cl002/ac005/executor.go
- pkg/action/cl002/ac005/explainer.go
- pkg/action/cl002/ac005/zz_generated.error.go
- pkg/action/cl002/ac005/zz_generated.executor.go
- pkg/action/cl002/ac005/zz_generated.explainer.go
This is the generated code for deleting all Tenant Cluster CRs.
> generate ac005 for cl002

- cmd/cl002/ac006/execute/zz_generated.command.go
- cmd/cl002/ac006/execute/zz_generated.error.go
- cmd/cl002/ac006/execute/zz_generated.flag.go
- cmd/cl002/ac006/execute/zz_generated.runner.go
- cmd/cl002/ac006/explain/zz_generated.command.go
- cmd/cl002/ac006/explain/zz_generated.error.go
- cmd/cl002/ac006/explain/zz_generated.flag.go
- cmd/cl002/ac006/explain/zz_generated.runner.go
- cmd/cl002/ac006/zz_generated.command.go
- cmd/cl002/ac006/zz_generated.error.go
- cmd/cl002/ac006/zz_generated.flag.go
- cmd/cl002/ac006/zz_generated.runner.go
- cmd/cl002/zz_generated.command.go
- pkg/action/cl002/ac006/executor.go
- pkg/action/cl002/ac006/explainer.go
- pkg/action/cl002/ac006/zz_generated.error.go
- pkg/action/cl002/ac006/zz_generated.executor.go
- pkg/action/cl002/ac006/zz_generated.explainer.go
This adds generated code for verifying all Tenant Cluster CRs got deleted.
> generate ac006 for cl002

- pkg/action/cl002/ac005/executor.go
- pkg/action/cl002/ac005/explainer.go
This is the same code as with `ac008` in `cl001`.
> implement cluster deletion for upgrade test

- pkg/action/cl002/ac006/error.go
- pkg/action/cl002/ac006/executor.go
- pkg/action/cl002/ac006/explainer.go
This checks that cluster deletion was successful eventually. The code is the same as for `ac009` in `cl001`.
> implement cluster checking successful cluster deletion for upgrade test

- pkg/action/cl001/ac002/error.go
- pkg/action/cl001/ac002/executor.go
- pkg/action/cl001/ac002/explainer.go
This got improved already in the patch upgrade test in cluster scope `cl002`. Just moving this to `cl001` now.
> fix create check for cl001

- pkg/action/cl001/ac000/explainer.go
- pkg/action/cl002/ac000/explainer.go
- pkg/action/cl002/ac000/plan.go
> make explainer output of test plans more informative

- pkg/action/cl002/ac004/explainer.go
- pkg/action/cl003/ac000/explainer.go
- pkg/action/cl003/ac004/explainer.go
> fix cluster scope injection

- cmd/cl001/zz_generated.command.go
> cl001-wire-ac009-ac010

- pkg/action/cl001/ac010/error.go
- pkg/action/cl001/ac010/executor.go
check if the AWS api call job was successful
for https://github.com/giantswarm/giantswarm/issues/13229
we could do cleaning here as well but I think we need another action
> cl001-ac010-kiam-check-job-aws-api

- pkg/action/cl001/ac002/executor.go
- pkg/action/cl001/ac003/executor.go
- pkg/action/cl001/ac004/executor.go
- pkg/action/cl001/ac006/executor.go
- pkg/action/cl001/ac007/executor.go
- pkg/action/cl001/ac008/executor.go
- pkg/action/cl001/ac009/executor.go
- pkg/action/cl001/ac010/executor.go
- pkg/action/cl001/ac011/executor.go
- pkg/action/cl002/ac002/executor.go
- pkg/action/cl003/ac002/executor.go
- pkg/client/tenant_cluster.go
- pkg/env/awscnfm_tenantcluster_kubeconfig.go
> add Tenant Cluster kube config support via environment varibale

- CHANGELOG.md
- pkg/key/key.go
> Fixgiraffedomain

- cmd/generate/action/template/pkg/action/explainer.go
- docs/using.md
- pkg/action/cl001/ac001/zz_generated.explainer.go
- pkg/action/cl001/ac005/crs.go
- pkg/action/cl002/ac001/zz_generated.explainer.go
- pkg/action/cl003/ac001/zz_generated.explainer.go
- pkg/action/cl004/ac001/zz_generated.explainer.go
- pkg/action/cl004/ac005/crs.go
- pkg/action/cl005/ac001/zz_generated.explainer.go
This is just a follow up of the latest refactorings so that the docs and the cluster descriptions are aligned again.
> align generated cluster description with recent structural changes

- cmd/cl006/zz_generated.command.go
- cmd/cl006/zz_generated.error.go
- cmd/cl006/zz_generated.flag.go
- cmd/cl006/zz_generated.runner.go
> single to ha cluster scope

- cmd/action/command.go
- cmd/action/create/cluster/command.go
- cmd/action/create/cluster/error.go
- cmd/action/create/cluster/flag.go
- cmd/action/create/cluster/onenodepool/command.go
- cmd/action/create/cluster/onenodepool/error.go
- cmd/action/create/cluster/onenodepool/flag.go
- cmd/action/create/cluster/onenodepool/runner.go
- cmd/action/create/cluster/runner.go
- cmd/action/create/command.go
- cmd/action/create/error.go
- cmd/action/create/flag.go
- cmd/action/create/runner.go
- cmd/action/error.go
- cmd/action/flag.go
- cmd/action/runner.go
- cmd/command.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for the first new action.
> add first action command

- cmd/command.go
- cmd/plan/command.go
- cmd/plan/error.go
- cmd/plan/flag.go
- cmd/plan/pl001/command.go
- cmd/plan/pl001/error.go
- cmd/plan/pl001/flag.go
- cmd/plan/pl001/runner.go
- cmd/plan/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for the first new plan.
> add first plan command

- cmd/action/verify/cluster/command.go
- cmd/action/verify/cluster/created/command.go
- cmd/action/verify/cluster/created/error.go
- cmd/action/verify/cluster/created/flag.go
- cmd/action/verify/cluster/created/runner.go
- cmd/action/verify/cluster/error.go
- cmd/action/verify/cluster/flag.go
- cmd/action/verify/cluster/runner.go
- cmd/action/verify/command.go
- cmd/action/verify/error.go
- cmd/action/verify/flag.go
- cmd/action/verify/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for the second new action.
> add second action command

- cmd/action/verify/master/command.go
- cmd/action/verify/master/error.go
- cmd/action/verify/master/flag.go
- cmd/action/verify/master/ready/command.go
- cmd/action/verify/master/ready/error.go
- cmd/action/verify/master/ready/flag.go
- cmd/action/verify/master/ready/runner.go
- cmd/action/verify/master/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for `awscnfm action verify master ready`.
> add structure for action verify master ready

- cmd/action/create/nodepool/command.go
- cmd/action/create/nodepool/defaultdataplane/command.go
- cmd/action/create/nodepool/defaultdataplane/error.go
- cmd/action/create/nodepool/defaultdataplane/flag.go
- cmd/action/create/nodepool/defaultdataplane/runner.go
- cmd/action/create/nodepool/error.go
- cmd/action/create/nodepool/flag.go
- cmd/action/create/nodepool/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for `awscnfm action create nodepool defaultdataplane`.
> add structure for create nodepool

- cmd/action/verify/command.go
- cmd/action/verify/kiam/command.go
- cmd/action/verify/kiam/error.go
- cmd/action/verify/kiam/flag.go
- cmd/action/verify/kiam/podandsecret/command.go
- cmd/action/verify/kiam/podandsecret/error.go
- cmd/action/verify/kiam/podandsecret/flag.go
- cmd/action/verify/kiam/podandsecret/runner.go
- cmd/action/verify/kiam/runner.go
- cmd/action/verify/worker/ready/command.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is the structure and logic for `awscnfm action verify kiam podandsecret`.
> add structure and logic for verify kiam podandsecret

- cmd/action/create/cluster/command.go
- cmd/action/create/cluster/singlecontrolplane/command.go
- cmd/action/create/cluster/singlecontrolplane/crs.go
- cmd/action/create/cluster/singlecontrolplane/error.go
- cmd/action/create/cluster/singlecontrolplane/flag.go
- cmd/action/create/cluster/singlecontrolplane/runner.go
> Add single master controlplane action

- README.md
- docs/introduction.md
- docs/structure.md
- docs/using.md
- docs/writing-tests.md
- pkg/client/tenant_cluster.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is the first batch of rewriting our docs aligning it with the new structure.
> first batch of docs improvements

- docs/structure.md
Based on https://github.com/giantswarm/awscnfm/pull/208. More docs changes. :all_the_things:
> fix structure docs

- CHANGELOG.md
- cmd/action/create/netpol/command.go
- cmd/action/create/netpol/curlrequest/command.go
- cmd/action/create/netpol/curlrequest/error.go
- cmd/action/create/netpol/curlrequest/flag.go
- cmd/action/create/netpol/curlrequest/job.go
- cmd/action/create/netpol/curlrequest/runner.go
towards https://github.com/giantswarm/giantswarm/issues/13955
Create a curl request job in the 'test' namespace and same job in the default namespace and test the network policy 'deny-from-all-namespaces' by connecting to the nginx test pod. The job in the 'test' namespace should successfully connect to the nginx test pod and the job in 'default' namespace should fail to connect to the nginx test pod.
> Action create netpol curlrequest

- CHANGELOG.md
- cmd/action/verify/command.go
- cmd/action/verify/netpol/command.go
- cmd/action/verify/netpol/curlrequest/command.go
- cmd/action/verify/netpol/curlrequest/error.go
- cmd/action/verify/netpol/curlrequest/flag.go
- cmd/action/verify/netpol/curlrequest/runner.go
- cmd/action/verify/netpol/error.go
- cmd/action/verify/netpol/flag.go
- cmd/action/verify/netpol/runner.go
towards: https://github.com/giantswarm/giantswarm/issues/13955
Verify that the curl test request jobs were executed as expected. 
Job inside of 'test' namespace should succeed and Job inside 'default' namespace should fail.
> Action verify netpol curlrequest

- cmd/action/create/kiam/awsapicall/error.go
- cmd/action/create/kiam/awsapicall/runner.go
- cmd/action/verify/kiam/awsapicall/runner.go
- cmd/action/verify/kiam/podandsecret/runner.go
- pkg/label/app.go
* refactor some code
* reuse already existing functions
* use control client instead of versioned
> refactor kiam code, use control runtime client

- cmd/action/verify/apps/installed/command.go
- cmd/action/verify/cluster/updated/command.go
- cmd/plan/pl001/plan.go
- cmd/plan/pl002/plan.go
- cmd/plan/pl003/command.go
- cmd/plan/pl003/plan.go
- cmd/plan/pl004/command.go
- cmd/plan/pl004/plan.go
- cmd/plan/pl005/plan.go
- cmd/plan/pl006/plan.go
adjust wait times and the order of some plans to  avoid flaky tests
> tune several plans, fix typos

- go.mod
- go.sum
> fix protobuf security issue

- CHANGELOG.md
- cmd/action/verify/apps/installed/runner.go
> add aws-ebs-csi-driver to expected apps list

- CHANGELOG.md
- cmd/action/verify/master/hostnetworkpod/runner.go
- cmd/action/verify/worker/hostnetworkpod/runner.go
> fix worker and master hostnetwork pods

- .circleci/config.yml
- CHANGELOG.md
- go.mod
- go.sum
> Add aliyun registry

- CHANGELOG.md
- cmd/plan/pl001/plan.go
Unfortunately time is quite tide for China we need to extend it a bit.
> extend backoff time

- CHANGELOG.md
- cmd/plan/pl001/flag.go
> Write cluster-id into path

- CHANGELOG.md
- cmd/plan/pl002/flag.go
- cmd/plan/pl003/flag.go
- cmd/plan/pl004/flag.go
- cmd/plan/pl005/flag.go
> Add output to all plans

- CHANGELOG.md
- cmd/action/verify/apps/command.go
- cmd/action/verify/apps/installed/runner.go
- cmd/action/verify/apps/running/command.go
- cmd/action/verify/apps/running/error.go
- cmd/action/verify/apps/running/flag.go
- cmd/action/verify/apps/running/runner.go
- cmd/plan/pl001/plan.go
Closes https://github.com/giantswarm/roadmap/issues/397
> verify running apps
