docs/completion.md
This is so you do not mix your custom completions with the bundled once. Works for me. 
```
$ l ~/.oh-my-zsh/custom/plugins/awscnfm/_awscnfm
-rw-r--r-- 1 xh3b4sd staff 3.5K Jul  1 11:03 /Users/xh3b4sd/.oh-my-zsh/custom/plugins/awscnfm/_awscnfm
```
```
$ awscnfm generate                                                                                                                                                                                  giantswarm-gauss
action   -- Generate a new action sub command.
cluster  -- Generate a new cluster sub command.
```
=> put zsh completions in custom folder

cmd/cl001/ac003/execute/zz_generated.command.go, cmd/cl001/ac003/execute/zz_generated.error.go, cmd/cl001/ac003/execute/zz_generated.flag.go, cmd/cl001/ac003/execute/zz_generated.runner.go, cmd/cl001/ac003/explain/zz_generated.command.go, cmd/cl001/ac003/explain/zz_generated.error.go, cmd/cl001/ac003/explain/zz_generated.flag.go, cmd/cl001/ac003/explain/zz_generated.runner.go, cmd/cl001/ac003/zz_generated.command.go, cmd/cl001/ac003/zz_generated.error.go, cmd/cl001/ac003/zz_generated.flag.go, cmd/cl001/ac003/zz_generated.runner.go, go.sum, pkg/action/cl001/ac001/executor.go, pkg/action/cl001/ac001/explainer.go, pkg/action/cl001/ac002/explainer.go, pkg/action/cl001/ac003/error.go, pkg/action/cl001/ac003/executor.go, pkg/action/cl001/ac003/explainer.go, pkg/action/cl001/ac003/zz_generated.error.go, pkg/action/cl001/ac003/zz_generated.executor.go, pkg/action/cl001/ac003/zz_generated.explainer.go
One of our next steps is to implement an action that actually creates the Tenant Cluster we want to test. So this needs to be action `ac001`. This PR shifts the actions to make space for the new functionality.
=> move commands to make space for cluster creation

go.mod, go.sum, pkg/action/cl001/ac001/executor.go, pkg/key/key.go, pkg/key/key_test.go
This PR adds functionality to the first action of our first cluster scope. With this we can define and create a Tenant Cluster. Right now the command does not work due to some issues with the k8s client management on program initialization. I want to fix this in the next PR separately.
=> implement action ac001 to create a tenant cluster

cmd/cl001/ac001/execute/zz_generated.runner.go, cmd/cl001/ac002/execute/zz_generated.runner.go, cmd/cl001/ac003/execute/zz_generated.runner.go, cmd/cl001/ac004/execute/zz_generated.runner.go, cmd/generate/action/template/cmd/execute/runner.go, docs/structure.md, pkg/action/client.go
With this we can implement the first action of a given cluster scope to define and create a Tenant Cluster. 
```
export AWSCNFM_TENANTCLUSTER=cl001
export AWSCNFM_KUBECONFIG=~/.kube/config
```
```
awscnfm cl001 ac001 execute
```
```
$ gsctl list clusters | grep cl001
cl001   giantswarm         awscnfm cluster cl001      12.0.0    2020 Jul 22, 14:43 UTC
```
=> create cluster using first action

cmd/generate/action/runner.go, cmd/generate/cluster/runner.go
I think I have a newer version of `golangci-lint` locally. So fixing this in advance. 
```
$ CGO_ENABLED=0 golangci-lint run -E gosec -E goconst
cmd/generate/cluster/runner.go:112:9: G306: Expect WriteFile permissions to be 0600 or less (gosec)
err = ioutil.WriteFile(path, buff.Bytes(), 0644)
^
cmd/generate/action/runner.go:158:10: G306: Expect WriteFile permissions to be 0600 or less (gosec)
err = ioutil.WriteFile(path, buff.Bytes(), 0644)
^
```
See https://gigantic.slack.com/archives/C3S23JE75/p1595507889147800.
=> fix linter issues

cmd/generate/action/flag.go, cmd/generate/action/runner.go, cmd/generate/cluster/runner.go, pkg/action/all.go
I noticed the more actions we add the more legwork it is to re-generate all actions. In order to not have to do this tedious kind of work we add a way to generate all actions of a cluster scope at once.
=> generate all actions at once

go.mod, pkg/action/cl001/ac000/plan.go, pkg/action/cl001/ac004/error.go, pkg/action/cl001/ac004/executor.go, pkg/action/cl001/ac004/explainer.go
```
$ awscnfm cl001 ac004 explain
Delete the tenant cluster of the current cluster scope by triggering the
deletion of the Cluster CR. This should ensure the following.
* Trigger deletion to all other CRs associated with the tenant cluster.
* Execute cleanup logic in all involved operators.
* Remove all cloud provider resources.
* Remove all CRs associated with the tenant cluster.
```
=> implement cluster deletion in ac004

cmd/generate/cluster/template/command.go
When generating new cluster, CircleCI fails due to new lines, see #62.
```bash
#!/bin/bash -eo pipefail
go get golang.org/x/tools/cmd/goimports && if [[ -n $(goimports -local github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -l .) ]]; then goimports -local github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -d . && exit 1; fi
go: downloading golang.org/x/tools v0.0.0-20200731060945-b5fad4ed8dd6
go: found golang.org/x/tools/cmd/goimports in golang.org/x/tools v0.0.0-20200731060945-b5fad4ed8dd6
go: golang.org/x/tools upgrade => v0.0.0-20200731060945-b5fad4ed8dd6
go: downloading golang.org/x/mod v0.3.0
diff -u cmd/cl002/zz_generated.command.go.orig cmd/cl002/zz_generated.command.go
--- cmd/cl002/zz_generated.command.go.orig
+++ cmd/cl002/zz_generated.command.go
@@ …
```
=> Fix goimports for generate cluster

cmd/cl001/ac005/execute/zz_generated.command.go, cmd/cl001/ac005/execute/zz_generated.error.go, cmd/cl001/ac005/execute/zz_generated.flag.go, cmd/cl001/ac005/execute/zz_generated.runner.go, cmd/cl001/ac005/explain/zz_generated.command.go, cmd/cl001/ac005/explain/zz_generated.error.go, cmd/cl001/ac005/explain/zz_generated.flag.go, cmd/cl001/ac005/explain/zz_generated.runner.go, cmd/cl001/ac005/zz_generated.command.go, cmd/cl001/ac005/zz_generated.error.go, cmd/cl001/ac005/zz_generated.flag.go, cmd/cl001/ac005/zz_generated.runner.go, cmd/cl001/zz_generated.command.go, pkg/action/cl001/ac005/executor.go, pkg/action/cl001/ac005/explainer.go, pkg/action/cl001/ac005/zz_generated.error.go, pkg/action/cl001/ac005/zz_generated.executor.go, pkg/action/cl001/ac005/zz_generated.explainer.go
I would like to introduce a new action in between. Basically I want to insert a new ac002 directly after cluster creation to check for the Tenant Cluster being up. Though at first we have to add ac005 so that all existing actions can be moved around. This is kind of missing and screws up the plan execution. **The PR here is only generated code.**
=> generate ac005 for cl001

pkg/action/cl001/ac002/executor.go, pkg/action/cl001/ac002/explainer.go
Follow up of https://github.com/giantswarm/awscnfm/pull/68. This here implements ac002 which got repurposed to check for cluster access directly after cluster creation.
=> check cluster access in ac002

main.go, pkg/action/cl001/ac000/plan.go, pkg/action/cl001/ac006/error.go, pkg/action/cl001/ac006/executor.go, pkg/action/cl001/ac006/explainer.go
I tested this on `gauss` since there are clusters running. The new action `ac006` checks if all CRs are gone. For a normally running cluster this command is expected to fail like shown below. 
```
$ export AWSCNFM_KUBECONFIG=~/.kube/config
$ export AWSCNFM_TENANTCLUSTER=6tjhj
```
```
$ awscnfm cl001 ac006 execute
Custom Resource Cleanup Error: Cluster
We do not expect any CR to be found anymore since we want to ensure that cluster deletion cleans up properly.
```
```
$ awscnfm cl001 ac006 explain
Check that all relevant CRs of the tenant cluster management got properly
cleaned up eventually during the transition of cluster deletion. This check
considers the following CRs.
* Cluster
* AWSCluster
* G8sControlPlane
* AWSControlPlane
* MachineDeployment
* AWSMachineDeployment
```
Here we also …
=> implement ac006 for checking if CRs are cleaned up during cluster deletion

cmd/command.go, cmd/insert/action/command.go, cmd/insert/action/error.go, cmd/insert/action/flag.go, cmd/insert/action/runner.go, cmd/insert/command.go, cmd/insert/error.go, cmd/insert/flag.go, cmd/insert/runner.go
Coming from https://gigantic.slack.com/archives/C7865GLSY/p1597218860004100. We want to have an `insert` command in order to inject new/empty actions in between. This PR only adds the command structure. Business logic follows in the next PRs.
=> add structure for insert command

pkg/project/project.go
For the release workflow we need a version value in our project package matching a semver regex.
See https://github.com/giantswarm/awscnfm/runs/975004186?check_suite_focus=true
=> Set a version in project package

CHANGELOG.md, pkg/action/cl001/ac008/executor.go
when running action 008, it should delete the test cluster but it was not working.
I was debugging and looking why it didn't work, adding logging in not found error
it says:
```
the server could not find the requested resource (delete clusters.cluster.x-k8s.io)
```
after I added the namespace I was able to delete the cluster.
=> include namespace to delete cluster

Makefile, cmd/insert/action/runner.go
Pulls in the fix made in https://github.com/giantswarm/devctl/pull/92
Also fixes a broken import in the "insert" command.
=> Fix binary naming in Makefile

pkg/action/cl001/ac003/executor.go, pkg/action/cl001/ac004/executor.go, pkg/action/cl001/ac005/executor.go, pkg/action/cl001/ac008/executor.go, pkg/action/cl001/ac009/executor.go
In https://github.com/giantswarm/awscnfm/pull/111 we generated the tenant cluster ID. Here we make use of it now.
=> use configured tenant cluster id

pkg/release/minor.go, pkg/release/minor_test.go, pkg/release/release.go
For upgrade tests we need to figure different versions based on the test case, e.g. we want to test a major or patch upgrade. This PR adds the release version lookup for minor release version differences. As expected the algorithm changed now and I aligned the patch version lookup as well. This may even imply greater opportunity for refactoring and simplification later on. **Please check if the test cases make sense to you.**
=> add minor release search

cmd/generate/action/template/pkg/action/explainer.go, pkg/action/cl001/ac001/zz_generated.explainer.go
In https://github.com/giantswarm/awscnfm/pull/123 we noticed that the generated constants we use for documentation purposes are not used when generating new actions. In order to fix this we define a fake constant to just use the documentation constant for assignment.
=> fix action generation when starting out

pkg/action/cl002/ac001/crs.go, pkg/action/cl002/ac001/executor.go, pkg/action/cl002/ac001/explainer.go
This PR implements cluster creation for the new cluster scope. The code is identical to the cluster creation in cluster scope `cl001`. I noticed I have to change the release version lookup for patch releases again. Will do this in the following PRs.
=> implement cluster creation in ac001 of cluster scope cl002

pkg/release/major.go, pkg/release/major_test.go, pkg/release/minor.go, pkg/release/minor_test.go, pkg/release/patch.go, pkg/release/patch_test.go, pkg/release/release.go
I noticed I just broke cluster creation with my last pull request. Background is the magic release resolver tries to figure out which is the right release version to use given certain circumstances. And this shit is way too complicated. With this PR the cluster creation is fine, though I do not like the code much. With `awscnfm` having project version `12.1.2-dev` and having release version `v12.1.4` as latest release on the control plane the cluster got created like shown below. 
```
$ gsctl list clusters
ID      ORGANIZATION   NAME                          RELEASE   CREATED
...
pyev0   giantswarm     awscnfm cl001 ac001 explain   12.1.4    2020 Sep 04, 08:25 UTC
```
=> fix release resolver

pkg/action/cl002/ac001/crs.go, pkg/action/cl002/ac001/explainer.go, pkg/action/cl002/ac003/executor.go, pkg/action/cl002/ac003/explainer.go
This implements triggering the cluster upgrade. The next step would be to implement an action that waits for the upgrade to complete. 
```
$ awscnfm cl002 ac003 explain
Upgrade the Tenant Cluster to the latest patch version.
* Fetch the Cluster CR.
* Set the desired cluster-operator version in the CR labels.
* Set the desired release version in the CR labels.
* Update the Cluster CR in the Control Plane.
```
=> implement cluster upgrade action in ac003

pkg/action/cl002/ac004/error.go, pkg/action/cl002/ac004/executor.go, pkg/action/cl002/ac004/explainer.go
Adding the business logic to ac004 in order to check for a successful cluster upgrade. I tested the negative result against a created Tenant Cluster that did not get upgraded so far. 
```
$ awscnfm cl002 ac004 explain
Check if the Tenant Cluster got successfully upgraded. Note that this
particular action is not meant to be reliably used for different purposes
than for the plan exection of cluster scope cl002. Executing this action
against a Tenant Cluster that got already upgraded may lead to wrong results
in case you want to assert an additional Tenant Cluster upgrade.
* Fetch the AWSCluster CR.
* Check if the latest cluster status condition is "Updated".
* Return an error if we see other cluster status conditions than "Updated".
```
```
$ awscnfm cl002 ac004 execute
Wrong Cluster Status …
```
=> check cluster upgrade successfully finished

main.go
Our conformance test tool was silent so far. With this PR we enable info logging, which proves quite useful when executing the test plan of a given cluster scope. Earlier when activating logging a whole lot of debug logs spammed the terminal while waiting for the test actions to succeed eventually. This is cleaner now. The `micrologger` work recently been done were towards the feedback improvements here. 
```
$ awscnfm cl002 ac000 execute
{"caller":"github.com/giantswarm/micrologger@v0.3.3/activation_logger.go:104","level":"info","message":"executing action `ac001`","time":"2020-09-16T13:29:17.124131+00:00"}
{"caller":"github.com/giantswarm/micrologger@v0.3.3/activation_logger.go:104","level":"info","message":"executing action `ac002`","time":"2020-09-16T13:29:19.754303+00:00"} …
```
=> configure activation logger for ignoring debug logs

pkg/action/cl001/ac001/executor.go, pkg/action/cl001/ac001/explainer.go, pkg/action/cl001/ac002/executor.go, pkg/action/cl001/ac003/executor.go, pkg/action/cl001/ac004/executor.go, pkg/action/cl001/ac005/executor.go, pkg/action/cl001/ac005/explainer.go, pkg/action/cl001/ac006/executor.go, pkg/action/cl001/ac007/executor.go, pkg/action/cl001/ac008/executor.go, pkg/action/cl001/ac009/executor.go, pkg/action/cl002/ac001/executor.go, pkg/action/cl002/ac001/explainer.go, pkg/action/cl002/ac002/executor.go, pkg/action/cl002/ac003/executor.go, pkg/action/cl002/ac004/executor.go, pkg/action/cl002/ac005/executor.go, pkg/action/cl002/ac006/executor.go, pkg/client/control_plane.go, pkg/env/awscnfm_kubeconfig.go
When running tests locally now you do not have to set the environment variable for the Control Plane kube config anymore. It is defaulted to the default location.
=> default control plane kube config

pkg/action/cl003/ac001/crs.go, pkg/action/cl003/ac003/executor.go, pkg/action/cl003/ac003/explainer.go
Since the cluster scopes are mostly self sufficient and we have a bit of duplicated code by design we simply run the minor upgrade test like the patch upgrade test. In this PR the minor version change is ensured according to the release resolver implementation we prepared some time ago.
=> ensure a minor release upgrade in cluster scope cl003

pkg/action/cl001/ac010/error.go
```
panic: {"kind":"jobNotCompleted","stack":[{"file":"/home/calvix/giantswarm/src/github.com/giantswarm/awscnfm/pkg/action/cl001/ac010/executor.go","line":74},{"file":"/home/calvix/giantswarm/src/github.com/giantswarm/awscnfm/pkg/action/cl001/ac010/executor.go","line":57},{"file":"/home/calvix/giantswarm/src/github.com/giantswarm/awscnfm/pkg/action/cl001/ac010/zz_generated.executor.go","line":49},{"file":"/home/calvix/giantswarm/src/github.com/giantswarm/awscnfm/cmd/cl001/ac010/execute/zz_generated.runner.go","line":61},{"file":"/home/calvix/giantswarm/src/github.com/giantswarm/awscnfm/cmd/cl001/ac010/execute/zz_generated.runner.go","line":34},{"file":"/home/calvix/giantswarm/src/github.com/giantswarm/awscnfm/main.go","line":78}]}
goroutine 1 [running]:
main.main() …
```
=> Add description to jobNotCompleted Error

pkg/action/cl001/ac011/executor.go, pkg/action/cl001/ac011/explainer.go, pkg/key/key.go
clean up kiam test resources
towards https://github.com/giantswarm/giantswarm/issues/13229
```
#: awscnfm cl001 ac000 execute
{"caller":"github.com/giantswarm/micrologger@v0.3.3/activation_logger.go:104","level":"info","message":"executing action `ac001`","time":"2020-10-01T14:41:35.82286+00:00"}
{"caller":"github.com/giantswarm/micrologger@v0.3.3/activation_logger.go:104","level":"info","message":"executing action `ac002`","time":"2020-10-01T14:41:38.623513+00:00"}
{"caller":"github.com/giantswarm/micrologger@v0.3.3/activation_logger.go:104","level":"info","message":"executing action `ac003`","time":"2020-10-01T15:00:18.129059+00:00"}
{"caller":"github.com/giantswarm/micrologger@v0.3.3/activation_logger.go:104","level":"info","message":"executing action …
```
=> implement-ac011-kiam-clean-resources

cmd/command.go, pkg/action/cl005/ac000/explainer.go, pkg/action/cl005/ac001/crs.go, pkg/action/cl005/ac003/executor.go, pkg/action/cl005/ac003/explainer.go
Towards https://github.com/giantswarm/giantswarm/issues/13460. 
```
$ awscnfm cl005 ac000 explain
Test plan for cl005 launches a basic Tenant Cluster in the previous major release
and upgrades the Tenant Cluster to the latest major release once it is up. Plan
execution might take up to 4h0m30s.
ACTION  RETRY  WAIT     COMMENT
ac001   2s     10s      create cluster CRs
ac002   3m0s   30m0s    check cluster access
ac003   2s     10s      trigger patch upgrade
ac004   10m0s  2h0m0s   check upgrade successful
ac005   2s     10s      delete cluster CRs
ac006   9m0s   1h30m0s  check CRs deleted
```
=> wire up new cluster scope cl005 for major upgrade test

pkg/action/cl004/ac002/executor.go, pkg/action/cl004/ac003/executor.go, pkg/action/cl004/ac004/executor.go, pkg/action/cl004/ac006/executor.go, pkg/action/cl004/ac007/executor.go, pkg/action/cl004/ac009/executor.go, pkg/action/cl004/ac010/executor.go, pkg/action/cl004/ac011/executor.go, pkg/action/cl005/ac002/executor.go
I delayed merging of the tenant client injection. Meanwhile work happened that got out of sync. Just following up where configuration is missing. The design might be a bit unfortunate when things like this can happen, though I do not have a good idea to resolve it quickly yet.
=> configure tenant client injection via environment

.circleci/config.yml, go.mod, go.sum
Follow up of https://github.com/giantswarm/awscnfm/pull/193.
=> fix nancy vulnerability reports by replacing correct etcd version

pkg/action/cl001/ac001/explainer.go, pkg/action/cl001/ac005/explainer.go, pkg/action/cl002/ac001/explainer.go, pkg/action/cl003/ac001/explainer.go, pkg/action/cl004/ac001/explainer.go, pkg/action/cl004/ac005/explainer.go, pkg/action/cl005/ac001/explainer.go
This PR removes all network dependencies from the explainers. The problem with having explainers depend on external resources is increased latency and in turn a worse user experience. With this PR execution times of even only printing the help usage dropped from **0.738** to **0.038** seconds. 
<pre>
$ time awscnfm cl001 ac001 -h
Create a basic Tenant Cluster with all its defaults.
Usage:
awscnfm cl001 ac001 [flags]
Flags:
-h, --help   help for ac001
awscnfm cl001 ac001 -h  0.13s user 0.07s system 27% cpu <b>0.738</b> total
</pre>
<pre>
$ time awscnfm cl001 ac001 -h
Create a basic Tenant Cluster with all its defaults.
Usage:
awscnfm cl001 ac001 [flags]
Flags:
-h, --help   help for ac001
awscnfm cl001 ac001 -h  0.02s user 0.02s system 97% cpu <b>0.038</b> total
</pre>
We do not print all …
=> remove network dependencies from explainer

pkg/action/cl001/ac000/executor.go, pkg/action/cl002/ac000/executor.go, pkg/action/cl003/ac000/executor.go, pkg/action/cl004/ac000/executor.go, pkg/action/cl005/ac000/executor.go, pkg/plan/executor.go
With the recent changes on the command structure the plan execution broke. This fixes the command lookup during plan execution. The problem was that commands could not be found because their location within the hierarchy changed.
=> fix command lookup during plan execution

cmd/plan/pl001/command.go, cmd/plan/pl001/plan.go, cmd/plan/pl001/runner.go, pkg/plan/executor.go
Based on https://github.com/giantswarm/awscnfm/pull/208. With this the new plan execution is set up. 
```
$ awscnfm plan pl001 -h
Test plan pl001 launches a basic Tenant Cluster and verifies basic criteria like
the correct number of nodes and pods are running. Plan execution might take up
to 30m10s.
ACTION                      RETRY  WAIT
create/cluster/onenodepool  2s     10s
verify/cluster/created      3m0s   30m0s
Usage:
awscnfm plan pl001 [flags]
Flags:
-h, --help   help for pl001
```
=> implement new plan execution

cmd/action/create/cluster/command.go, cmd/action/create/cluster/defaultcontrolplane/command.go, cmd/action/create/cluster/defaultcontrolplane/crs.go, cmd/action/create/cluster/defaultcontrolplane/error.go, cmd/action/create/cluster/defaultcontrolplane/flag.go, cmd/action/create/cluster/defaultcontrolplane/runner.go, cmd/plan/pl001/plan.go
Based on https://github.com/giantswarm/awscnfm/pull/208. Renaming here for more clarity. The action itself should only create the Control Plane. Though in the test plan we should always use two actions together in order to get a cluster with Node Pools. As discussed we cannot just use a cluster without Node Pools because of some implementation details.
=> rename action for more clarity

cmd/action/verify/command.go, cmd/action/verify/worker/command.go, cmd/action/verify/worker/error.go, cmd/action/verify/worker/flag.go, cmd/action/verify/worker/ready/command.go, cmd/action/verify/worker/ready/error.go, cmd/action/verify/worker/ready/flag.go, cmd/action/verify/worker/ready/runner.go, cmd/action/verify/worker/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for `awscnfm action verify worker ready`.
=> add structure for action verify worker ready

cmd/action/verify/master/command.go, cmd/action/verify/master/hostnetworkpod/command.go, cmd/action/verify/master/hostnetworkpod/error.go, cmd/action/verify/master/hostnetworkpod/flag.go, cmd/action/verify/master/hostnetworkpod/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for `awscnfm action verify master hostnetworkpod`.
=> add structure for verify master hostnetworkpod

cmd/action/verify/worker/command.go, cmd/action/verify/worker/hostnetworkpod/command.go, cmd/action/verify/worker/hostnetworkpod/error.go, cmd/action/verify/worker/hostnetworkpod/flag.go, cmd/action/verify/worker/hostnetworkpod/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is the command structure and logic for `awscnfm action verify worker hostnetworkpod`.
=> add structure and logic for verify worker hostnetworkpod

cmd/action/command.go, cmd/action/delete/cluster/command.go, cmd/action/delete/cluster/error.go, cmd/action/delete/cluster/flag.go, cmd/action/delete/cluster/runner.go, cmd/action/delete/command.go, cmd/action/delete/error.go, cmd/action/delete/flag.go, cmd/action/delete/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for `awscnfm action delete cluster`.
=> add structure for action delete cluster

cmd/action/create/command.go, cmd/action/create/kiam/awsapicall/command.go, cmd/action/create/kiam/awsapicall/error.go, cmd/action/create/kiam/awsapicall/flag.go, cmd/action/create/kiam/awsapicall/runner.go, cmd/action/create/kiam/command.go, cmd/action/create/kiam/error.go, cmd/action/create/kiam/flag.go, cmd/action/create/kiam/runner.go, cmd/action/delete/command.go, cmd/action/delete/kiam/awsapicall/command.go, cmd/action/delete/kiam/awsapicall/error.go, cmd/action/delete/kiam/awsapicall/flag.go, cmd/action/delete/kiam/awsapicall/runner.go, cmd/action/delete/kiam/command.go, cmd/action/delete/kiam/error.go, cmd/action/delete/kiam/flag.go, cmd/action/delete/kiam/runner.go, cmd/action/verify/kiam/awsapicall/command.go, cmd/action/verify/kiam/awsapicall/error.go, cmd/action/verify/kiam/awsapicall/flag.go, cmd/action/verify/kiam/awsapicall/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for three new kiam actions. Together they test that calls to the AWS API can be made. 
```
awscnfm action create kiam awsapicall
awscnfm action verify kiam awsapicall
awscnfm action delete kiam awsapicall
```
=> add structure for kiam actions

cmd/plan/pl001/runner.go, pkg/plan/executor.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This adds some validation capabilities so that we fail fast in case something is not wired up correctly. Otherwise it might happen that a plan is being executed for two hours and only then someone finds out that there was a typo in the action path.
=> add validation for plans to fail fast

cmd/action/command.go, cmd/action/update/cluster/command.go, cmd/action/update/cluster/error.go, cmd/action/update/cluster/flag.go, cmd/action/update/cluster/major/command.go, cmd/action/update/cluster/major/error.go, cmd/action/update/cluster/major/flag.go, cmd/action/update/cluster/major/runner.go, cmd/action/update/cluster/minor/command.go, cmd/action/update/cluster/minor/error.go, cmd/action/update/cluster/minor/flag.go, cmd/action/update/cluster/minor/runner.go, cmd/action/update/cluster/patch/command.go, cmd/action/update/cluster/patch/error.go, cmd/action/update/cluster/patch/flag.go, cmd/action/update/cluster/patch/runner.go, cmd/action/update/cluster/runner.go, cmd/action/update/command.go, cmd/action/update/error.go, cmd/action/update/flag.go, cmd/action/update/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This is only the command structure for `awscnfm action update cluster`. 
```
$ awscnfm action update cluster
Update Tenant Clusters within a Control Plane.
Usage:
awscnfm action update cluster [flags]
awscnfm action update cluster [command]
Available Commands:
major       Update a Tenant Cluster to the latest major release.
minor       Update a Tenant Cluster to the latest minor release.
patch       Update a Tenant Cluster to the latest patch release.
Flags:
-h, --help   help for cluster
Use "awscnfm action update cluster [command] --help" for more information about a command.
```
=> add structure for update commands

cmd/action/create/cluster/defaultcontrolplane/crs.go, cmd/action/create/cluster/defaultcontrolplane/flag.go, cmd/action/create/cluster/defaultcontrolplane/runner.go, cmd/action/create/cluster/singlecontrolplane/crs.go, cmd/action/create/cluster/singlecontrolplane/flag.go, cmd/action/create/cluster/singlecontrolplane/runner.go, pkg/valid/error.go, pkg/valid/id.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This allows to provide a cluster ID for cluster creation. The new plan execution will consider this and make it easier to execute plans. 
```
$ awscnfm action create cluster defaultcontrolplane -c ""
```
```
$ awscnfm action create cluster defaultcontrolplane -c " "
panic: {"kind":"invalidFlagsError","annotation":"-c/--tenant-cluster invalid id error: must start with letter","stack":[{"file":"/Users/xh3b4sd/go/src/github.com/giantswarm/awscnfm/cmd/action/create/cluster/defaultcontrolplane/flag.go","line":28},{"file":"/Users/xh3b4sd/go/src/github.com/giantswarm/awscnfm/cmd/action/create/cluster/defaultcontrolplane/runner.go","line":27},{"file":"/Users/xh3b4sd/go/src/github.com/giantswarm/awscnfm/main.go","line":78}]}
goroutine 1 …
```
=> let cluster ids be given for cluster creation

cmd/plan/pl005/runner.go
Based on https://github.com/giantswarm/awscnfm/pull/208. This fixes the missing cluster ID generation in plan `pl005`.
=> fix plan pl005 by injecting new cluster ID

CHANGELOG.md, cmd/action/create/command.go, cmd/action/create/netpol/command.go, cmd/action/create/netpol/defaultnetpol/command.go, cmd/action/create/netpol/defaultnetpol/error.go, cmd/action/create/netpol/defaultnetpol/flag.go, cmd/action/create/netpol/defaultnetpol/namespace.go, cmd/action/create/netpol/defaultnetpol/netpol.go, cmd/action/create/netpol/defaultnetpol/pod.go, cmd/action/create/netpol/defaultnetpol/runner.go, cmd/action/create/netpol/defaultnetpol/service.go, cmd/action/create/netpol/error.go, cmd/action/create/netpol/flag.go, cmd/action/create/netpol/runner.go, pkg/key/error.go, pkg/key/key.go
towards https://github.com/giantswarm/giantswarm/issues/13955
Create a test resources for a default network policy that denies traffic from other namespaces.
Created resources:
* namespace 'test'
* network policy 'deny-from-other-namespaces' in namespace 'test'
* nginx pod running in 'test' namespace
* service for the nginx to test the connection to the pod
the other actions will follow soon after
=> Action create netpol defaultnetpol

cmd/action/create/cluster/defaultcontrolplane/runner.go, cmd/action/create/cluster/singlecontrolplane/runner.go
Executing the conformance tests I noticed something was a little funky with the logs. The cluster ID had a newline at the end like `7qgep\n`. 
```
$ awscnfm plan pl001
{"caller":"github.com/giantswarm/micrologger@v0.3.4/activation_logger.go:104","level":"info","message":"executing action `create/cluster/defaultcontrolplane`","time":"2020-11-17T15:11:02.600622+00:00"}
{"caller":"github.com/giantswarm/micrologger@v0.3.4/activation_logger.go:104","level":"info","message":"creating crs for tenant cluster 7qgep\n","time":"2020-11-17T15:11:03.02416+00:00"}
{"caller":"github.com/giantswarm/micrologger@v0.3.4/activation_logger.go:104","level":"info","message":"executing action `verify/cluster/created`","time":"2020-11-17T15:11:03.781059+00:00"}
...
```
=> do not print newline in logs

cmd/plan/pl001/command.go, cmd/plan/pl002/command.go, cmd/plan/pl003/command.go, cmd/plan/pl004/command.go, cmd/plan/pl005/command.go, cmd/plan/pl006/command.go, pkg/plan/executor.go, pkg/plan/step.go
I was wondering if this is good or not. I want to let the crowd decide. If you have to ask what changed it might not even be worth it. 😄 
```
$ awscnfm plan pl001 -h
Test plan pl001 launches a basic Tenant Cluster and verifies basic criteria like
the correct number of nodes and pods are running. Plan execution might take up
to 2h47m20s.
ACTION                              RETRY  WAIT
create cluster defaultcontrolplane  2s     10s
verify cluster created              3m0s   30m0s
verify master ready                 2s     10s
create nodepool defaultdataplane    2s     10s
verify worker ready                 3m0s   30m0s
verify master hostnetworkpod        1m0s   15m0s
verify worker hostnetworkpod        2s     10s
verify kiam podandsecret            2s     10s
create kiam awsapicall …
```
=> make plan help usage more readable

cmd/action/verify/master/hostnetworkpod/runner.go, cmd/action/verify/worker/hostnetworkpod/runner.go
since the latest version, cert-exporter is no longer running  on host network so removing from the list
related PRs:
https://github.com/giantswarm/k8scloudconfig/pull/839
https://github.com/giantswarm/cert-exporter/pull/67
https://github.com/giantswarm/releases/pull/489/files#diff-0558904bd7b9ba9c4978a85be9be05734a316391b7e871a1a6045c461bcafb7cR74-R79
Also, I will create a PR to  the aws-operator
this means the `master` will fail for versions < 13.0.0
=> remove-cert-exporter-from-hostpodnetworklist

CHANGELOG.md, cmd/action/update/cluster/major/runner.go, cmd/action/update/cluster/minor/runner.go, cmd/action/update/cluster/patch/runner.go, docs/environment_variables.md, pkg/env/awscnfm_update_releaseversion.go
Fixes https://github.com/giantswarm/giantswarm/issues/14546. Since we namespaced the env vars, we can now take a separate env var for the updates. When running conformance tests for updates you would now set two env vars. Successfully tested on `gauss`, though [the test failed in the end due to other reasons](https://github.com/giantswarm/giantswarm/issues/13008#issuecomment-740609550). 
```
export AWSCNFM_CREATE_RELEASEVERSION=v12.5.2
export AWSCNFM_UPDATE_RELEASEVERSION=v12.6.0
```
=> add update specific env var for release version

cmd/plan/pl001/plan.go, cmd/plan/pl002/plan.go, cmd/plan/pl003/plan.go, cmd/plan/pl004/plan.go, cmd/plan/pl005/plan.go, cmd/plan/pl006/plan.go, pkg/plan/executor.go, pkg/plan/step.go, pkg/plan/step_action.go, pkg/plan/step_condition.go
Fixes https://github.com/giantswarm/giantswarm/issues/14431. You see below how "verify cluster created" is being executed with backoff after perceiving a fake error. After that all actions are skipped except the once configured with `Condition: "always-execute"`. This is contrary to the earlier behaviour of stopping the execution of the plan on error. 
```
$ awscnfm plan pl006
{"caller":"github.com/giantswarm/micrologger@v0.4.0/activation_logger.go:117","level":"info","message":"executing action `create cluster singlecontrolplane`","time":"2020-12-09T15:50:11.761566+00:00"}
{"caller":"github.com/giantswarm/micrologger@v0.4.0/activation_logger.go:117","level":"info","message":"executing action `verify cluster created`","time":"2020-12-09T15:50:11.76164+00:00"} …
```
=> allow plan steps to always be executed

cmd/plan/pl001/error.go, cmd/plan/pl001/flag.go, cmd/plan/pl001/runner.go, cmd/plan/pl002/error.go, cmd/plan/pl002/flag.go, cmd/plan/pl002/runner.go, cmd/plan/pl003/error.go, cmd/plan/pl003/flag.go, cmd/plan/pl003/runner.go, cmd/plan/pl004/error.go, cmd/plan/pl004/flag.go, cmd/plan/pl004/runner.go, cmd/plan/pl005/error.go, cmd/plan/pl005/flag.go, cmd/plan/pl005/runner.go, cmd/plan/pl006/error.go, cmd/plan/pl006/flag.go, cmd/plan/pl006/runner.go, pkg/plan/executor.go
While I was debugging throttling errors in `awscnfm` I noticed that the plan execution against existing clusters did not work. This PR fixes the problem of the env var `AWSCNFM_TENANTCLUSTER` not being respected during consecutive test polan executions.
=> consider cluster id from env when executing plan

cmd/action/create/kiam/awsapicall/job.go
During testing I noticed the job to check if kiam is able to call the AWS able was failing. Digging into that it looked like the job was terminating prematurely. We were setting `activeDeadlineSeconds` which prevents all backoffs to retry so the test could never work. With the fixes here the plan execution is fine again.  
See https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup.
=> fix failing kiam action

CHANGELOG.md, cmd/action/create/nodepool/defaultdataplane/crs.go, pkg/key/key.go
Giantswarm Organization is not the expected one for conformance tests, we need to use a seperate one `conformance-testing`.
=> fix failing awscnfm in china
